# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('am1', models.CharField(default='Üres', max_length=30)),
                ('am2', models.CharField(default='Üres', max_length=30)),
                ('am3', models.CharField(default='Üres', max_length=30)),
                ('am4', models.CharField(default='Üres', max_length=30)),
                ('am5', models.CharField(default='Üres', max_length=30)),
                ('am6', models.CharField(default='Üres', max_length=30)),
                ('am7', models.CharField(default='Üres', max_length=30)),
                ('am8', models.CharField(default='Üres', max_length=30)),
                ('pm6_1', models.CharField(default='Üres', max_length=30)),
                ('pm6_2', models.CharField(default='Üres', max_length=30)),
                ('pm6_3', models.CharField(default='Üres', max_length=30)),
                ('pm6_4', models.CharField(default='Üres', max_length=30)),
                ('pm8_1', models.CharField(default='Üres', max_length=30)),
                ('pm8_2', models.CharField(default='Üres', max_length=30)),
                ('pm8_3', models.CharField(default='Üres', max_length=30)),
                ('pm8_4', models.CharField(default='Üres', max_length=30)),
                ('pm8_5', models.CharField(default='Üres', max_length=30)),
                ('pm8_6', models.CharField(default='Üres', max_length=30)),
                ('pm8_7', models.CharField(default='Üres', max_length=30)),
                ('pm8_8', models.CharField(default='Üres', max_length=30)),
            ],
        ),
    ]
