# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 08:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('am1', models.CharField(max_length=30)),
                ('am2', models.CharField(max_length=30)),
                ('am3', models.CharField(max_length=30)),
                ('am4', models.CharField(max_length=30)),
                ('am5', models.CharField(max_length=30)),
                ('am6', models.CharField(max_length=30)),
                ('am7', models.CharField(max_length=30)),
                ('am8', models.CharField(max_length=30)),
                ('pm1_6', models.CharField(max_length=30)),
                ('pm2_6', models.CharField(max_length=30)),
                ('pm3_6', models.CharField(max_length=30)),
                ('pm4_6', models.CharField(max_length=30)),
                ('pm1_8', models.CharField(max_length=30)),
                ('pm2_8', models.CharField(max_length=30)),
                ('pm3_8', models.CharField(max_length=30)),
                ('pm4_8', models.CharField(max_length=30)),
                ('pm5_8', models.CharField(max_length=30)),
                ('pm6_8', models.CharField(max_length=30)),
                ('pm7_8', models.CharField(max_length=30)),
                ('pm8_8', models.CharField(max_length=30)),
                ('day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersDailyShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(max_length=20)),
                ('shift', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usersdailyshift',
            unique_together=set([('user', 'day')]),
        ),
    ]
