# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beo_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyshift',
            name='pm1_6',
        ),
        migrations.RemoveField(
            model_name='dailyshift',
            name='pm1_8',
        ),
        migrations.RemoveField(
            model_name='dailyshift',
            name='pm2_6',
        ),
        migrations.RemoveField(
            model_name='dailyshift',
            name='pm2_8',
        ),
        migrations.RemoveField(
            model_name='dailyshift',
            name='pm3_6',
        ),
        migrations.RemoveField(
            model_name='dailyshift',
            name='pm3_8',
        ),
        migrations.RemoveField(
            model_name='dailyshift',
            name='pm4_6',
        ),
        migrations.RemoveField(
            model_name='dailyshift',
            name='pm4_8',
        ),
        migrations.RemoveField(
            model_name='dailyshift',
            name='pm5_8',
        ),
        migrations.RemoveField(
            model_name='dailyshift',
            name='pm6_8',
        ),
        migrations.RemoveField(
            model_name='dailyshift',
            name='pm7_8',
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='pm6_1',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='pm6_2',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='pm6_3',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='pm6_4',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='pm8_1',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='pm8_2',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='pm8_3',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='pm8_4',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='pm8_5',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='pm8_6',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AddField(
            model_name='dailyshift',
            name='pm8_7',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='am1',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='am2',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='am3',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='am4',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='am5',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='am6',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='am7',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='am8',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='day',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='pm8_8',
            field=models.CharField(choices=[('Ü', 'Üres')], default='Ü', max_length=30),
        ),
    ]
