# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beo_admin', '0002_auto_20171124_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyshift',
            name='day',
            field=models.DateField(),
        ),
    ]
