# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now, max_length=20)),
                ('is_working', models.BooleanField(default=False)),
                ('shift', models.CharField(choices=[('DE', 'délelőtt'), ('DU', 'délután')], default='DE', max_length=10)),
                ('hours', models.SmallIntegerField(choices=[(6, 6), (8, 8)], default=6)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyRequest',
            fields=[
                ('week', models.SmallIntegerField(default=48, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dailyrequest',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.WeeklyRequest'),
        ),
    ]
