# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(max_length=20)),
                ('is_working', models.BooleanField(default=False)),
                ('shift', models.CharField(choices=[('DE', 'délelőtt'), ('DU', 'délután')], default='DE', max_length=10)),
                ('hours', models.SmallIntegerField(choices=[(6, 6), (8, 8)], default=6)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
